sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: fjzTEshFOWUtoyYRFgINQ6j6auW89IxZiYmdHtFgEr6tBLrhdYDp+xumFCKyG28bH+rlwpUuxn2X3UBxTTOxOLIn4T/MF3V3T38KEnQU1ghVMomnKGdj4NLQmk/68p5BGHVH3gWo9ha8nGJGEr/N2LveQAPZXSkeiqgvkzR8ULBEcNZce7HNPFjBgeQt8G+QkQUXvmpRamZHaJ+88ERcBrtYELVes0Gg3S/B9gn+eoFuWJDWqe9bq1em1HTzU4WSmstpRlgaPlA1s5qlFNN83ZXczUegDIfXxMSz8QXb94V1eHX/QoDvnjaYe9cS6xDC9o/QtaOBLLnd8hAoFvKvhnUoIVW9DTdqe2FOQ1Y0WCwkNKrCS9Sia8qAMSIkuJDhS+SdE07qP4dC8rBW/eYnN2/P/i1we1U7vBymBzOHQ2CsPOOv/LJXGnrPw0BId44nc+W5lCBqmtbCmeSP1Eymhz8kz9rKd/vdRpE59DqSQ7+D8TpVT/w4LZnw8RKdfWH4jQbf8KB/TDo7dztdjr8PQlbkJWWOUPu0ZkGSmIYyezPYhaP9clsjbpu8R5rQ0t/X38W6mT1+0jx1XhOCDH6DT9hEyacny4iTCMXs8Mu0aZi02wQJEw8z8x71hmWl9/mbtIiI5XTt3xixPwxEgXoBTjXSV2w1CszVKJ6Qdk7RLrY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/---_1982
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy